export const genreList = [
  { id: 1, title: '판타지' },
  { id: 2, title: 'SF' },
  { id: 3, title: '로맨스' },
  { id: 4, title: '스릴러' },
  { id: 5, title: '미스터리' },
  { id: 6, title: '추리' },
  { id: 7, title: '역사' },
  { id: 8, title: '공포' },
  { id: 9, title: '드라마' },
  { id: 10, title: '모험' },
  { id: 11, title: '학원' },
  { id: 12, title: '코미디' },
  { id: 13, title: '스포츠' },
  { id: 14, title: '성인' },
  { id: 15, title: '철학' },
  { id: 16, title: '정치' },
  { id: 17, title: '종교' },
  { id: 18, title: '요리' },
  { id: 19, title: '로맨스판타지' },
  { id: 20, title: '현대판타지' },
  { id: 21, title: '무협' },
  { id: 22, title: 'BL' },
  { id: 23, title: '액션' },
  { id: 24, title: '기타' }
];